# Generated by Django 5.2.8 on 2025-11-26 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('connection_type', models.CharField(blank=True, choices=[('FIBER', 'Fiber'), ('ADSL', 'ADSL'), ('VSAT', 'VSAT'), ('VDSL', 'VDSL'), ('3G', '3G'), ('other', 'Other')], max_length=20, null=True)),
                ('service_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('wan_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('default_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('host_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vsat_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_0', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_2', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_3', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_4', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_5', models.CharField(blank=True, max_length=50, null=True)),
                ('tunnel_6', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tid', models.CharField(max_length=20, unique=True)),
                ('atm_name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('Industrial_Park', 'Industrial Park'), ('Financial_Institution', 'Financial Institution'), ('University', 'University'), ('Hotel', 'Hotel'), ('Military_Base', 'Military Base'), ('Office_Building', 'Office Building'), ('Hospital', 'Hospital'), ('other', 'Other')], max_length=50, null=True)),
                ('atm_brand', models.CharField(default='NCR', max_length=50)),
                ('deployment_status', models.CharField(choices=[('DEPLOYED', 'Deployed'), ('NOT_DEPLOYED', 'Not Deployed'), ('IN_MAINTENANCE', 'In Maintenance')], default='DEPLOYED', max_length=20)),
                ('service_number', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_type', models.CharField(blank=True, choices=[('FIBER', 'Fiber'), ('ADSL', 'ADSL'), ('VSAT', 'VSAT'), ('VDSL', 'VDSL'), ('3G', '3G'), ('other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbe.branch')),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': 'ATMs',
                'db_table': 'atms',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbe.branch')),
            ],
            options={
                'db_table': 'contact_persons',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbe.district'),
        ),
    ]
